import Anthropic from '@anthropic-ai/sdk';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { stripMarkdownInline } from './translator';
import { readTitle } from './numerology';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

const CLAUDE_MODEL = 'claude-sonnet-5';

export interface GeneratedEssay {
  title: string;
  excerpt: string;
  content: string;
  tags: string[];
  entities: string[];
  pullQuote: string;
}

// ── Model call ────────────────────────────────────────────────────────────────
// Essays are generated by Claude when ANTHROPIC_API_KEY is set, falling back to
// Gemini otherwise (the daily column and translator still use Gemini directly).
//
// Claude returns the essay through a TOOL CALL rather than as JSON inside prose.
// That is the whole point of using it here: the API guarantees the tool input
// matches the schema, so the malformed-JSON failures that plagued the Gemini path
// — unescaped quotes inside a 2,000-word HTML string, which cost us whole essays
// and a retry budget — cannot occur by construction.
const ESSAY_TOOL: Anthropic.Tool = {
  name: 'publish_essay',
  description: 'Publish the finished essay to Catzye.',
  input_schema: {
    type: 'object',
    properties: {
      title: { type: 'string', description: 'Engaging, specific title, prefixed "Part N: "' },
      excerpt: { type: 'string', description: 'Search-optimised description, under 155 characters' },
      content: {
        type: 'string',
        description:
          'The essay body as HTML. Only <h2>, <h3>, <p>, <strong>, <em> tags. No markdown, no <html> or <body> wrapper.',
      },
      tags: { type: 'array', items: { type: 'string' }, description: '5 short tags' },
      entities: {
        type: 'array',
        items: { type: 'string' },
        description: 'Manga, anime, studio, creator names referenced',
      },
      pullQuote: { type: 'string', description: 'One memorable sentence from the essay, 15-35 words' },
    },
    required: ['title', 'excerpt', 'content', 'tags', 'entities', 'pullQuote'],
  },
};

let anthropic: Anthropic | null = null;
function claude(): Anthropic | null {
  if (!process.env.ANTHROPIC_API_KEY) return null;
  anthropic ??= new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  return anthropic;
}

async function generate(prompt: string): Promise<Record<string, unknown>> {
  const client = claude();

  if (client) {
    const res = await client.messages.create({
      model: CLAUDE_MODEL,
      max_tokens: 8000,
      tools: [ESSAY_TOOL],
      tool_choice: { type: 'tool', name: 'publish_essay' },
      messages: [{ role: 'user', content: prompt }],
    });
    const block = res.content.find((b) => b.type === 'tool_use');
    if (!block || block.type !== 'tool_use') {
      throw new Error('Claude did not return the publish_essay tool call');
    }
    return block.input as Record<string, unknown>;
  }

  const result = await model.generateContent({
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    generationConfig: { responseMimeType: 'application/json' },
  });
  return parseJson(result.response.text());
}

// The model reliably emits a complete JSON object but sometimes leaves a raw `"`
// inside a string value — it quotes a manga title mid-sentence and forgets to
// escape it. The object is otherwise sound, so rather than throw the whole essay
// away, walk it and escape any quote that isn't a real structural delimiter. A
// closing quote is only structural if the next non-space character is one of
// , } ] : — anything else means we're still inside the string.
function escapeStrayQuotes(json: string): string {
  const out: string[] = [];
  let inString = false;
  let escaped = false;

  for (let i = 0; i < json.length; i++) {
    const ch = json[i];

    if (escaped) { out.push(ch); escaped = false; continue; }
    if (ch === '\\') { out.push(ch); escaped = true; continue; }

    if (ch === '"') {
      if (!inString) {
        inString = true;
        out.push(ch);
      } else {
        let j = i + 1;
        while (j < json.length && /\s/.test(json[j])) j++;
        if (j >= json.length || [',', '}', ']', ':'].includes(json[j])) {
          inString = false;
          out.push(ch);
        } else {
          out.push('\\"'); // stray quote inside a string value
        }
      }
      continue;
    }

    if (inString && (ch === '\n' || ch === '\r')) {
      out.push(ch === '\n' ? '\\n' : '\\r');
      continue;
    }

    out.push(ch);
  }

  return out.join('');
}

export function parseJson(raw: string): Record<string, unknown> {
  const text = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();
  try { return JSON.parse(text); } catch { /* fall through */ }
  const block = text.match(/\{[\s\S]*\}/);
  if (block) {
    try { return JSON.parse(block[0]); } catch { /* fall through */ }
    try {
      const fixed = block[0].replace(
        /("(?:[^"\\]|\\.)*")/g,
        (m) => m.replace(/\n/g, '\\n').replace(/\r/g, '\\r'),
      );
      return JSON.parse(fixed);
    } catch { /* fall through */ }
    try { return JSON.parse(escapeStrayQuotes(block[0])); } catch { /* fall through */ }
  }
  throw new Error('Could not parse Gemini JSON response');
}

export async function generateEssay(
  seriesTitle: string,
  seriesDescription: string,
  topic: string,
  partNumber: number,
  totalParts: number,
): Promise<GeneratedEssay> {
  const prompt = `You are a senior manga and anime culture writer for Catzye.com, a professional magazine for manga and anime enthusiasts.

You are writing Part ${partNumber} of ${totalParts} in the essay series: "${seriesTitle}"
Series overview: ${seriesDescription || seriesTitle}

Topic for this part: "${topic}"

Requirements:
- 1800–2400 words of rich, original prose
- Name specific manga titles (with Japanese titles in parentheses where helpful), authors, publishers, historical dates, and cultural context
- Academic depth with engaging, readable style — not a Wikipedia summary
- Where relevant, trace how the topic evolved across different manga eras (pre-war, postwar, bubble era, digital era)
- Connect to broader Japanese cultural, social, or historical forces
- Structure: engaging 2-paragraph introduction, 4–5 H2 sections with descriptive headers, strong conclusion that ties back to the series theme
- DO NOT use markdown — only HTML tags: <h2>, <h3>, <p>, <strong>, <em>

Return ONLY this JSON object (no markdown fences, no extra text):
{
  "title": "Part ${partNumber}: [an engaging, specific title for this essay]",
  "excerpt": "1–2 sentence description optimised for search, under 155 chars",
  "content": "<h2>First Section</h2><p>...</p><h2>Second Section</h2><p>...</p>",
  "tags": ["tag1", "tag2", "tag3", "tag4", "tag5"],
  "entities": ["Manga Title", "Author Name", "Publisher Name"],
  "pullQuote": "one memorable sentence from the essay, 15–35 words"
}`;

  const parsed = await generate(prompt);

  const tags = Array.isArray(parsed.tags) ? (parsed.tags as string[]).slice(0, 8) : [];
  const entities = Array.isArray(parsed.entities) ? (parsed.entities as string[]).slice(0, 12) : [];

  return {
    title: stripMarkdownInline(String(parsed.title ?? topic)),
    excerpt: stripMarkdownInline(String(parsed.excerpt ?? '').slice(0, 160)),
    content: String(parsed.content ?? ''),
    tags,
    entities,
    pullQuote: stripMarkdownInline(String(parsed.pullQuote ?? '')),
  };
}

// ── Craft essay generator ─────────────────────────────────────────────────────
// For "The Grammar of the Page": formal criticism of how comics actually work on
// a reader — panel, gutter, page turn, line. The failure mode here is not
// fabricated statistics (as in the industry series) but empty abstraction, so
// the prompt forces every claim back down onto a specific page the reader can go
// and look at.
export async function generateCraftEssay(
  seriesTitle: string,
  seriesDescription: string,
  topic: string,
  partNumber: number,
  totalParts: number,
  anchors: string[],
): Promise<GeneratedEssay> {
  const anchorBlock = anchors.length
    ? anchors.map((a) => `• ${a}`).join('\n')
    : '(no fixed anchors — choose your own well-known examples)';

  const prompt = `You are a comics critic writing for Catzye.com — the register of Scott McCloud or Thierry Groensteen, but plainer and less academic. You write about how manga actually works on a reader: the panel, the gutter, the page turn, the line. Formal criticism, close reading, no mysticism and no industry gossip.

You are writing Part ${partNumber} of ${totalParts} in the essay series: "${seriesTitle}"
Series overview: ${seriesDescription || seriesTitle}

Topic for this part: "${topic}"

THINGS THIS ESSAY MUST GENUINELY ENGAGE WITH (not merely name-drop):
${anchorBlock}

Requirements:
- 1800–2400 words of rich, original prose.
- CLOSE READING IS THE POINT. Every abstract claim must land on a specific, nameable moment a reader could go and look at — this series, this scene, this kind of page. Vague gestures at "dynamic paneling" are the failure mode. Describe what is actually on the page and what it does to the eye.
- Explain mechanism: not that a technique is effective, but HOW it produces its effect — where the eye goes, what the reader is made to supply, what the timing does.
- Do not invent facts, quotes, or page numbers. Describe techniques and well-known scenes you are confident about. If unsure of a specific detail, write about the technique in general rather than fabricating a citation.
- Where useful, contrast manga's conventions with those of American or European comics — but resist the lazy claim that either is simply better.
- Be honest when a technique is a cliché, or when a famous effect is cruder than its reputation.
- Structure: a 2-paragraph introduction, 4–5 H2 sections with descriptive headers, and a conclusion that ties back to the series theme.
- DO NOT use markdown — only HTML tags: <h2>, <h3>, <p>, <strong>, <em>.

Return ONLY this JSON object (no markdown fences, no extra text):
{
  "title": "Part ${partNumber}: [an engaging, specific title for this essay]",
  "excerpt": "1–2 sentence description optimised for search, under 155 chars",
  "content": "<h2>First Section</h2><p>...</p><h2>Second Section</h2><p>...</p>",
  "tags": ["manga craft", "tag2", "tag3", "tag4", "tag5"],
  "entities": ["Manga/Creator names referenced"],
  "pullQuote": "one memorable sentence from the essay, 15–35 words"
}`;

  const parsed = await generate(prompt);

  const rawTags = Array.isArray(parsed.tags) ? (parsed.tags as string[]) : [];
  const tags = Array.from(new Set(['manga craft', ...rawTags])).slice(0, 8);
  const entities = Array.isArray(parsed.entities) ? (parsed.entities as string[]).slice(0, 12) : [];

  return {
    title: stripMarkdownInline(String(parsed.title ?? topic)),
    excerpt: stripMarkdownInline(String(parsed.excerpt ?? '').slice(0, 160)),
    content: String(parsed.content ?? ''),
    tags,
    entities,
    pullQuote: stripMarkdownInline(String(parsed.pullQuote ?? '')),
  };
}

// ── Screen essay generator ────────────────────────────────────────────────────
// For "The Grammar of the Screen": the companion to the craft series, but for
// anime as a moving image — timing, layouts, compositing, sound. Same failure
// mode as the craft series (empty abstraction), plus a specific one of its own:
// gushing about "the sakuga" without saying what the animation is actually doing.
export async function generateScreenEssay(
  seriesTitle: string,
  seriesDescription: string,
  topic: string,
  partNumber: number,
  totalParts: number,
  anchors: string[],
): Promise<GeneratedEssay> {
  const anchorBlock = anchors.length
    ? anchors.map((a) => `• ${a}`).join('\n')
    : '(no fixed anchors — choose your own well-known examples)';

  const prompt = `You are an animation critic writing for Catzye.com. You write about how anime works as a moving image — timing, spacing, layouts, compositing, colour, sound, editing. Craft criticism of the frame and the cut, not industry gossip and not plot summary.

You are writing Part ${partNumber} of ${totalParts} in the essay series: "${seriesTitle}"
Series overview: ${seriesDescription || seriesTitle}

Topic for this part: "${topic}"

THINGS THIS ESSAY MUST GENUINELY ENGAGE WITH (not merely name-drop):
${anchorBlock}

Requirements:
- 1800–2400 words of rich, original prose.
- CLOSE READING IS THE POINT. Every abstract claim must land on a specific, nameable moment a viewer could go and watch. Describe what is actually happening on screen — how many frames a movement is held, where the cut falls, what the camera does, what the sound is doing under it.
- The signature failure of anime criticism is gushing about "the sakuga" without ever saying what the animation is actually doing. Do not do this. Explain mechanism: why this timing reads as weight, why that hold reads as dread.
- Use the real vocabulary correctly and explain it in passing: animating on ones, twos, and threes; genga and douga; layouts; the storyboard; compositing; smears; effects animation.
- Do not invent facts, quotes, episode numbers, or credits. If unsure whether a specific animator worked on a specific cut, describe the technique rather than fabricating an attribution. Never invent a named person's credit.
- Where useful, contrast anime's conventions with Western animation traditions — but resist the lazy claim that either is simply better, and resist the myth that limited animation is merely cheap.
- Be honest when an effect is a cliché, or when a famous sequence is cruder than its reputation.
- Structure: a 2-paragraph introduction, 4–5 H2 sections with descriptive headers, and a conclusion that ties back to the series theme.
- DO NOT use markdown — only HTML tags: <h2>, <h3>, <p>, <strong>, <em>.

Return ONLY this JSON object (no markdown fences, no extra text):
{
  "title": "Part ${partNumber}: [an engaging, specific title for this essay]",
  "excerpt": "1–2 sentence description optimised for search, under 155 chars",
  "content": "<h2>First Section</h2><p>...</p><h2>Second Section</h2><p>...</p>",
  "tags": ["anime craft", "tag2", "tag3", "tag4", "tag5"],
  "entities": ["Anime/Studio/Director names referenced"],
  "pullQuote": "one memorable sentence from the essay, 15–35 words"
}`;

  const parsed = await generate(prompt);

  const rawTags = Array.isArray(parsed.tags) ? (parsed.tags as string[]) : [];
  const tags = Array.from(new Set(['anime craft', ...rawTags])).slice(0, 8);
  const entities = Array.isArray(parsed.entities) ? (parsed.entities as string[]).slice(0, 12) : [];

  return {
    title: stripMarkdownInline(String(parsed.title ?? topic)),
    excerpt: stripMarkdownInline(String(parsed.excerpt ?? '').slice(0, 160)),
    content: String(parsed.content ?? ''),
    tags,
    entities,
    pullQuote: stripMarkdownInline(String(parsed.pullQuote ?? '')),
  };
}

// ── Industry essay generator ──────────────────────────────────────────────────
// For "The Serialization Machine": reported cultural criticism about the
// commercial and editorial forces that shape manga. No mystical frame — the
// claims here are meant to be checkable, so the prompt names the concrete cases
// the essay has to engage with and forbids inventing figures.
export async function generateIndustryEssay(
  seriesTitle: string,
  seriesDescription: string,
  topic: string,
  partNumber: number,
  totalParts: number,
  anchors: string[],
): Promise<GeneratedEssay> {
  const anchorBlock = anchors.length
    ? anchors.map((a) => `• ${a}`).join('\n')
    : '(no fixed anchors — choose your own well-documented cases)';

  const prompt = `You are a senior manga and anime industry writer for Catzye.com. You write reported cultural criticism about how manga actually gets made, sold, and killed — the commercial and editorial machinery behind the art. Think of the register of a good long-form trade feature: specific, sceptical, unsentimental, but written by someone who plainly loves the medium.

You are writing Part ${partNumber} of ${totalParts} in the essay series: "${seriesTitle}"
Series overview: ${seriesDescription || seriesTitle}

Topic for this part: "${topic}"

ANCHOR CASES — the essay must engage seriously with each of these, not merely name-drop them:
${anchorBlock}

Requirements:
- 1800–2400 words of rich, original prose.
- Be concrete: real titles (with Japanese where helpful), creators, editors, magazines, publishers, dates, and documented events. Explain mechanisms, not vibes — how the reader survey actually feeds back into the page order, what an editor's job really consists of, where the money comes from.
- ACCURACY IS THE POINT. Do not invent statistics, sales figures, quotes, or events. If you are not confident in a precise number, describe the phenomenon qualitatively instead. It is far better to write "sales collapsed" than to fabricate a figure. Never attribute a quote to a named person unless it is genuinely well documented.
- Acknowledge uncertainty where it exists: much of this industry is opaque, and where the record is thin, say so rather than papering over it.
- Connect the mechanics to the art: show how a commercial constraint produced a specific creative result — a rushed ending, a bloated arc, a tone shift, a masterpiece made under duress.
- Structure: a 2-paragraph introduction, 4–5 H2 sections with descriptive headers, and a conclusion that ties back to the series theme.
- DO NOT use markdown — only HTML tags: <h2>, <h3>, <p>, <strong>, <em>.

Return ONLY this JSON object (no markdown fences, no extra text):
{
  "title": "Part ${partNumber}: [an engaging, specific title for this essay]",
  "excerpt": "1–2 sentence description optimised for search, under 155 chars",
  "content": "<h2>First Section</h2><p>...</p><h2>Second Section</h2><p>...</p>",
  "tags": ["manga industry", "tag2", "tag3", "tag4", "tag5"],
  "entities": ["Manga/Creator/Publisher/Magazine names referenced"],
  "pullQuote": "one memorable sentence from the essay, 15–35 words"
}`;

  // Ask Gemini for a JSON mime type rather than trusting it to emit clean JSON
  // inside prose. Without this, long essays containing quotes and apostrophes
  // fail to parse often enough to burn the whole retry budget.
  const parsed = await generate(prompt);

  const rawTags = Array.isArray(parsed.tags) ? (parsed.tags as string[]) : [];
  const tags = Array.from(new Set(['manga industry', ...rawTags])).slice(0, 8);
  const entities = Array.isArray(parsed.entities) ? (parsed.entities as string[]).slice(0, 12) : [];

  return {
    title: stripMarkdownInline(String(parsed.title ?? topic)),
    excerpt: stripMarkdownInline(String(parsed.excerpt ?? '').slice(0, 160)),
    content: String(parsed.content ?? ''),
    tags,
    entities,
    pullQuote: stripMarkdownInline(String(parsed.pullQuote ?? '')),
  };
}

// ── Numerology-aware essay generator ──────────────────────────────────────────
// A variant of generateEssay for "The Numbers Behind the Manga" series. It reads
// the numerology of each named subject IN CODE and injects the real numbers into
// the prompt, so the model writes accurate readings instead of inventing them.
function numerologyDataBlock(subjects: string[]): string {
  const rows = subjects
    .map((s) => (s || '').trim())
    .filter(Boolean)
    .map((s) => {
      const r = readTitle(s);
      return `• "${s}" → Destiny ${r.destiny} (${r.profile.title}); Heart's Desire ${r.heartDesire}; Personality ${r.dream}. Vibration: ${r.profile.vibration}.`;
    });
  return rows.join('\n') || '(no specific subjects — write about the numbers themselves)';
}

export async function generateNumerologyEssay(
  seriesTitle: string,
  seriesDescription: string,
  topic: string,
  partNumber: number,
  totalParts: number,
  subjects: string[],
): Promise<GeneratedEssay> {
  const dataBlock = numerologyDataBlock(subjects);

  const prompt = `You are a senior manga and anime culture writer for Catzye.com. You are writing an essay that reads the medium through the lens of numerology — literate, grown-up cultural criticism, NOT horoscope copy or pseudoscience.

You are writing Part ${partNumber} of ${totalParts} in the essay series: "${seriesTitle}"
Series overview: ${seriesDescription || seriesTitle}

Topic for this part: "${topic}"

NUMEROLOGY DATA (authoritative — these numbers were computed with standard Pythagorean numerology; use ONLY these, never compute or invent your own numbers, and do not contradict them):
${dataBlock}

Numerology key you may reference: 1 Leader/Pioneer, 2 Diplomat, 3 Creative Communicator, 4 Builder, 5 Freedom Seeker, 6 Nurturer, 7 Analyst/Seeker, 8 Visionary/Achiever, 9 Humanitarian/Sage; master numbers 11 (Visionary), 22 (Master Builder), 33 (Master Teacher). Destiny = whole name; Heart's Desire = vowels; Personality = consonants.

Requirements:
- 1600–2200 words of rich, original prose.
- Roughly 60% genuine manga/anime culture writing (accurate specifics: real titles with Japanese where helpful, authors, studios, publishers, dates, cultural context) and 40% the numerological reading, used as an organizing frame.
- Weave the computed numbers above into the argument — quote the exact Destiny numbers given and connect each number's archetype to what the work/creator/studio actually is and does.
- Be honest about the game: numerology is a lens for paying attention, a source of coincidences worth a second look, NOT a claim that the universe assigns fate. Keep an intelligent, slightly playful, never breathless tone. Do not invent facts, quotes, or figures.
- Structure: a 2-paragraph introduction, 4–5 H2 sections with descriptive headers, and a conclusion that ties back to the series theme.
- DO NOT use markdown — only HTML tags: <h2>, <h3>, <p>, <strong>, <em>.

Return ONLY this JSON object (no markdown fences, no extra text):
{
  "title": "Part ${partNumber}: [an engaging, specific title for this essay]",
  "excerpt": "1–2 sentence description optimised for search, under 155 chars",
  "content": "<h2>First Section</h2><p>...</p><h2>Second Section</h2><p>...</p>",
  "tags": ["numerology", "tag2", "tag3", "tag4", "tag5"],
  "entities": ["Manga/Anime/Studio/Creator names referenced"],
  "pullQuote": "one memorable sentence from the essay, 15–35 words"
}`;

  const parsed = await generate(prompt);

  const rawTags = Array.isArray(parsed.tags) ? (parsed.tags as string[]) : [];
  const tags = Array.from(new Set(['numerology', ...rawTags])).slice(0, 8);
  const entities = Array.isArray(parsed.entities) ? (parsed.entities as string[]).slice(0, 12) : [];

  return {
    title: stripMarkdownInline(String(parsed.title ?? topic)),
    excerpt: stripMarkdownInline(String(parsed.excerpt ?? '').slice(0, 160)),
    content: String(parsed.content ?? ''),
    tags,
    entities,
    pullQuote: stripMarkdownInline(String(parsed.pullQuote ?? '')),
  };
}
